### PR TITLE
Symfony 3.1 upgrade

### PR DESCRIPTION
**Pull request by pueppiblue**
Had no access to knutschsoft remote repo. So i'll open a forked PR.

### CODE REVIEW

**Comment by robertfausk** [comment]
Build fails. Can you fix please?
It seems that you installed packages which are not compatible with PHP smaller than version 7. 
Unluckely there is no detailed information in your commit message about updated packages.
At least ```ocramius/package-versions``` does not fit smaller PHP versions.
E.g. ``` ocramius/package-versions 1.1.1 requires php ~7.0 -> your PHP version (5.5.21) does not satisfy that requirement.``` at https://travis-ci.org/knutschsoft/swapp/jobs/150615617

**Comment by robertfausk** [comment]
Hint: You can try to set php version in composer and run composer update again. https://getcomposer.org/doc/06-config.md#platform

E.g. something like:
```JSON
    "config": {
        "bin-dir": "bin",
        "platform": {
            "php": "5.5.21"
        }
    },
```

**Comment by pueppiblue** [comment]
This fixed the issue with ocramius/package-versions. But we now seem to have bundle(s) with deprecated methods instead. Also testCreateWalk is failing. It appears it can't find the link with
[data-test="create-walk"]. Maybe another issue with changed dependency versions.

**Comment by robertfausk** [comment]
Can you fix the failing test? Do you need help with debug?

**Comment by robertfausk** [comment]
Btw. I don't think that the test fails because of changed dependencies cause i think in another PR this test also fails.

**Comment by pueppiblue** [comment]
dump($crawler->html()):

in the output there is no Button for "createWalk".
Also the tests did not fail before composer updates. Even written tests in the other pr which did not fail.

**Comment by pueppiblue** [comment]
after loading fictures and authenticating the crawler probably looks at a page like this:
![walks_noTeams] (https://picload.org/image/rrlwwogo/walks_noteams.png)

and since the link-button the crawler is searching for depends on team length:
```
{% if teams|length %}
            <a class="btn "
                ...
                data-test="create-walk">Runde beginnen
            </a>
{% endif %}
```
    $crawler = $crawler->filter('[data-test="create-walk"]');
can't find any matching node.
I can confirm that the fixtures (team.yml) are loaded into database, but there seems to be something
awry with
    ` $teams = $user->getTeams();`
in
     `WalkController::homeScreenAction`

will look a bit further into debugging the action

**Comment by pueppiblue** [comment]
Tracked it down now. 
```
WalkController::homeScreenaction:
$teams = $user->getTeams();
```
apparently the template only gets teh teams for the current user.

The teammembers are randomized by the fixtures. So if user "admin" is not part of any team
`teams|length` evaluates to false and no button is in the template and thus the crawler will have an empty 
node list after trying to filter for 
`$crawler = $crawler->filter('[data-test="create-walk"]');
`.
So we can either rewrite the test or include the user "admin" in every team via fixtures.

**Comment by pueppiblue** [comment]
Deprecaton notices for test concerning 
`singularify():
- defined in `Symfony\Component\PropertyAccess\StringUtil`
- used in:
    + `Symfony\Component\PropertyAccess\StringUtilTest` 
    + `Nelmio/Alice/Instances/Populator/Methods/ArrayAdd.php`

Guess updating hautelook/AliceBundle to a 3.1 compatible version will do the trick.

**Comment by pueppiblue** [comment]
Composer loads the tag 2.1.4 from nelmio/alice 2.x branch because
in this [commit](https://github.com/nelmio/alice/commit/f4ad6c434f7b9eb0bf6954ec9ecb1187e678cdd4)
minimum php-version required was set to 5.6. for the actual version. 
The deprecation fix did not make it into tag 2.1.4.
So either we:
-  ignore the deprecation for now :-1: 
- let go of alice/faker tests :-1: 
- we update to minimum php 5.6 :+1:

**Pull request merged**
